### ISSUE TITLE
Make post images in widgets clickable

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/flymag#11]

**Comment by Lucaz97** [comment]
i was able to do that changing some php for the widget recent post slider, i am trying to find where is located the code for the carousel under the nav bar

**Comment by rodica-andronache** [comment]
Hi @Lucaz97 ,

The code for the carousel is situated in this file https://github.com/Codeinwp/flymag/blob/production/inc/slider/slider.php

Regards,
Rodica

**Comment by Lucaz97** [comment]
Thank you very much, I appreciate

**Comment by Lucaz97** [comment]
Hi,
I apologize for bothering you again, I can't figure out how to make a page
like the contacts one in the online demo of the Flymag theme,
If you could help me out that would be amazing
Thank you
Luca

**Comment by abaicus** [comment]
Hello @Lucaz97,

The contact page from the demo is just a page with shortcodes from the Pirate Forms and Intergeo Maps plugins. 

Have an awesome day!
Andrei
