### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by robi09** [Codeinwp/flymag#12]
Hi guys, i have this PHP error the first time when i add the widget in front-page sidebar:

Notice: Trying to get property of non-object in D:\work\htdocs\macho\ReviveWP\wp-content\themes\flymag\functions.php on line 352

**Comment by rodica-andronache** [comment]
@robi09 thanks, but could you please give more details? I couln't replicate this. What issue have you tried to add and in what sidebar. There is no frontpage sidebar
