### ISSUE TITLE
Two options for favicons

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/flymag#18]
There is both a favicon uploading option in **Customizer->General** and Site identity. WordPress default is in site identity so we should maybe remove this from the general options section.

**Comment by rodica-andronache** [comment]
we should remove the option from General -> upload your favicon, and migrate that option in the default option from wordpress -> Site identiy. Something like this maybe https://github.com/Codeinwp/bookrev/commit/2ff45a4218a4f4825bc78f9ba04f6a5120dfcf9a
