### ISSUE TITLE
Compatability with 'All in one SEO'

### ISSUE THREAD

**Issue by johnmathews** [Codeinwp/flymag#24]
The theme appears to not work correctly with the 'All in One SEO' plugin. Because of how widely used the plug in is, I think the issue may be with the theme. Apologies if this is incorrect.

The issue is getting the test in the browser tab to display correctly. On the home page I want the site title, on a blog post, I want the post title followed by the site title (separated by a |). This is not possible.

In the plugin, changing the page title format or the post title format, effects the home page title. Also post title format does not render correctly and displays a double delimiter '|' between the post and site titles.

Does header.php need changing?

**Comment by rodica-andronache** [comment]
Hi @johnmathews ,

Thank you for contacting us. We'll investigate this issue in the next weeks and let you know about the outcome.

Best regards,
Rodica
