### ISSUE TITLE
About page - free vs pro layout

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/flymag#32]

**Comment by bogdanpopa90** [comment]
I have a proposal for Getting started tag and also something similar for Support tab:
- use icons for every Step (screenshot);
- use same button design as Go to Customiser, for the ther two links.

![about-proposal](https://cloud.githubusercontent.com/assets/23031578/23213030/147eda9e-f912-11e6-9cd5-6ba9ca06e334.jpg)
