### ISSUE TITLE
Clickable carousel images

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/flymag#41]
@rodica-andronache maybe an option in customizer to turn it on

**Comment by rodica-andronache** [comment]
@UVLabs I'm not sure I understand this. You mean, those images http://prntscr.com/f3kjme to be able to click on them and go to the post link? i think it's made like this to be able to scroll from a post to the other in the carousel. Is something suggested by a user? pro or lite?

**Comment by UVLabs** [comment]
Yes clicking the images, some free users: https://wordpress.org/support/topic/make-the-images-on-carrousel-clickable/

**Comment by rodica-andronache** [comment]
Here we should: 
- make all frontpage images clickable(not just the ones from the carousel).
- fix this alignment issue http://prntscr.com/f70t7s
- redo the screenshot for the lite version This should be very simple, not working more than 2hours on both lite and pro.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu here you should also make sure travis passes . Make the change Marius mentioned on the development channel
` Uncaught Error: Class 'PHP_CodeSniffer_Exception' not found `
se pare ca a fost release la phpcs aseara si sunt niste erori cu wordpress coding standard
o solutie ar fi sa schimbati in travis in loc de `pear install pear/PHP_CodeSniffer`
in `pear install pear/PHP_CodeSniffer-2.8.1`

and make sure travis is passing

**Comment by rodica-andronache** [comment]
@cristian-ungureanu please make the same changes in the pro version too

**Comment by cristian-ungureanu** [comment]
@rodica-andronache done

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I think you missed this area on top http://prntscr.com/faqsj0 . At least here http://forks.themeisle.com/cristian-ungureanu/flymag/development/ it doesn't seem to work

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I fixed it
