### ISSUE TITLE
Upsells in customizer

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/flymag#6]
@ineagu it's ok to add uplsells right?

**Comment by ineagu** [comment]
yes

On Fri, Dec 11, 2015 at 9:33 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> it's ok to add uplsells right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/flymag/issues/6>.
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
